version: "3.9"

services:
  api:
    build: .
    container_name: pairfecto-api
    env_file:
      - .env  # reuse your local env; values can be overridden below
    environment:
      # Point FastAPI to the Compose network mongo instance
      - MONGO_URI=mongodb://mongo:27017/pairfecto
    ports:
      - "8000:8000"  # host:container
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: pairfecto-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
